### PR TITLE
Fixed: wrong service being used for fetching background job details(#188)

### LINKED ISSUE #188: Delay in Order Fulfillment due to Pre-order App Code Error
## Current behavior
The execution of the fulfillment workflow for orders is affected, even the single order fulfillment is taking longer than expected. **Assumption**: Using  `ftpExportProductThresholdCsv` service in preorder app is not required. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by ymaheshwari1**
### Related Issues

Closes #188 

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/services/JobService.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ const prepareFetchJobsQuery = () => {
   const lastActionTimestamp = (store.state as any).order.lastActionTimestamp;
   return {
     "inputFields": {
-      "serviceName": "ftpExportProductThresholdCsv",
+      "serviceName": "brokerReleasedOrderItems",
```
Comment (dixitdeepak) [inline src/services/JobService.ts:24]: Changes looks good to me

**Review by dixitdeepak — APPROVED** [review]
