### PR TITLE
Fixed eCommerce options are not visible on settings page (#85zrhj216)

### LINKED ISSUE #95: ECommerce options are not visible on settings page
## Current behavior

On settings page, the ecommerce select does not list any of the options

## Expected behavior

All the possible ecommerce store options should be displayed on the settings page

## Steps to reproduce the issue

- Login into the app
- Go to settings page
- Click on select ecommerce option and see that the list is empty

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

**Screenshot:**

image

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #95 

### Short Description and Why It's Useful

Fixed eCommerce store options not appearing on the settings page. 

#### Before
Preorder Management - HotWax Commerce
#### After
Preorder Management - HotWax Commerce (1)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by ymaheshwari1 — APPROVED** [review]

File: src/store/modules/user/actions.ts [hunk 1]
```diff
@@ -95,6 +95,14 @@ const actions: ActionTree<UserState, RootState> = {
       let stores = [] as any;
       if(storeResp.status === 200 && !hasError(storeResp) && storeResp.data.docs?.length > 0) {
         stores = [...storeResp.data.docs]
+        
+        resp.data.stores = [
+          ...(stores ? stores : []),
+          {
+            productStoreId: "",
+            storeName: "None"
```
Comment (adityasharma7) [inline src/store/modules/user/actions.ts:103]: With the preorder app's use case, the user will get data specific to the product store or all the data, consider the products page if a product store is selected, app products belonging to the selected store are fetched if not all the products are fetched.

```suggestion
            storeName: "All"
```

File: src/store/modules/user/actions.ts [hunk 2]
```diff
@@ -95,6 +95,14 @@ const actions: ActionTree<UserState, RootState> = {
       let stores = [] as any;
       if(storeResp.status === 200 && !hasError(storeResp) && storeResp.data.docs?.length > 0) {
         stores = [...storeResp.data.docs]
+        
+        resp.data.stores = [
+          ...(stores ? stores : []),
```
Comment (adityasharma7) [inline src/store/modules/user/actions.ts:100]: It seems there is no possibility stores will not exist, we could skip this check

**Review by adityasharma7 — CHANGES_REQUESTED** [review]

File: src/store/modules/user/actions.ts (hunk 1 above)
Comment (k2maan) [reply src/store/modules/user/actions.ts]: Yes, sir, understood.

File: src/store/modules/user/actions.ts (hunk 2 above)
Comment (k2maan) [reply src/store/modules/user/actions.ts]: Updated sir.

**Review by adityasharma7 — APPROVED** [review]
